
[snowflake]
user = "put username here"
password = "put password here"
account = "ndsoebe-rai-dev-ecosystem-aws-us-east-2-consumer"
warehouse = "arq_wh"
database = "ARQ"
schema = "SOURCE"
role = "team_arq"





















[plantid]
api_key = "dzpG57WfbkdZ09Yg6zAT2kbWHNHlqWMr7bQJEI2fzH6GcCntNO"

[gemini]
api_key = "AIzaSyDDRaZnklkKV_r4B5bCmTf6hab3ypBg4x8"


